name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # 4️⃣ Clean and rebuild
      - name: Prepare build directory
        run: |
          rm -rf build
          mkdir -p build

      # 5️⃣ Convert Markdown to HTML
      - name: Build site
        run: go run main.go

      # 6️⃣ Copy static files correctly
      - name: Copy static assets
        run: cp -r static/* build/

      # 7️⃣ List build contents for debugging
      - name: Show build output
        run: ls -R build

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
